## FEATURE SCALING METHODS

- FEATURE SCALING is the process of bringing all numerical feature to a similar range
- it helps machine learning algorithms perfoem better and converg faster

## NORMALIZATION(Min-Max Scaling)

- Normalization scales the value beteween 0 and 1

  - EXAMPLE:-
  
              - 20 --> 0.2

              - 50 --> 0.5

              - 100 --> 1.0


Smallest value becomes 0 and largest become 1

## STANDARDIZATION

STANDARDIZATION transfrom the data to have a mean of 0 and STANDARD DEVIATION OF 1

- after STANDARDIZATION the data is centered around zero

### when to use

- use Normalization when the data has a fixed range

- use STANDARDIZATION when the data contain outliers or follows a Normal Distribution

In [1]:
from sklearn.preprocessing import MinMaxScaler,StandardScaler
import numpy as np

In [2]:
data= np.array([[10],[20],[30],[40],[50]])


In [3]:
#Normalization

minmax=MinMaxScaler()
print(minmax.fit_transform(data))

[[0.  ]
 [0.25]
 [0.5 ]
 [0.75]
 [1.  ]]


In [4]:
#STANDARDIZATION

standard=StandardScaler()
print(standard.fit_transform(data))

[[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]


## task

### NORMALIZATION


QUESTION  
mark=35 50 65 80 95

In [5]:
mark= np.array([[35],[50],[65],[80],[95]])

minmax=MinMaxScaler()
print(minmax.fit_transform(mark))



[[0.  ]
 [0.25]
 [0.5 ]
 [0.75]
 [1.  ]]


### STANDARDIZATION


question

heights- 150 160 170 180 190

In [8]:
height= np.array([[150],[160],[170],[180],[190]])

standard=StandardScaler()
print(standard.fit_transform(height))

[[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]


### nomalization + standization

In [10]:
salary= ([15000], [25000], [45000], [35000], [55000])


minmax=MinMaxScaler()
print(minmax.fit_transform(salary))


[[0.  ]
 [0.25]
 [0.75]
 [0.5 ]
 [1.  ]]


In [11]:
standard=StandardScaler()
print(standard.fit_transform(salary))

[[-1.41421356]
 [-0.70710678]
 [ 0.70710678]
 [ 0.        ]
 [ 1.41421356]]


### TASK 2

In [4]:
from sklearn.preprocessing import MinMaxScaler,StandardScaler
import numpy as np

In [5]:
abc=([[12],[14],[18],[20],[22]])


standard=StandardScaler()
print(standard.fit_transform(abc))


[[-1.40182605]
 [-0.86266219]
 [ 0.21566555]
 [ 0.75482941]
 [ 1.29399328]]


In [6]:
minmax1=MinMaxScaler()
print(minmax1.fit_transform(abc))

[[0. ]
 [0.2]
 [0.6]
 [0.8]
 [1. ]]
