# numpy installation

In [ ]:
# !pip install numpy


[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

In [3]:
np.__version__


'2.4.4'

# creating Arrays

1D ARRAY

In [ ]:
array1=np.array([1,2,3,4,5])
array2=np.array([10,12,13,14,15])
print(array1)
print(array2)

[1 2 3 4 5]
[10 12 13 14 15]


2D ARRAY

In [ ]:
array3=np.array([[1,2,3,4,5],[6,7,8,9,10]])
array3


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
print(array3.shape) #(no of rows,no of coloumn )
print(array3.size)# no of total elements
print(array3.dtype)#datatype of the element
print(array3.ndim)#dimension of the array
print(array3.itemsize) #size of each element(in bytes)

(2, 5)
10
int64
2
8


3D array


In [11]:
array4=np.array([[[1,2,3,4,5],
                [6,7,8,9,10],
                [1,2,3,4,5],
                [6,7,8,9,10]],
                
                [[1,2,3,4,5],
                [6,7,8,9,10],
                [1,2,3,4,5],
                [6,7,8,9,10]]])
array4

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]])

In [ ]:
print(array4.shape)# (no of layers,no of row,np of column)

(2, 4, 5)


zeros

In [ ]:
array5=np.zeros(5)
array5

array5=np.zeros((3,3))
array5[[0,1,2],[0,1,2]]=1
array5




array([[1., 2., 1., 2., 1., 2.],
       [3., 4., 3., 4., 3., 4.],
       [5., 6., 5., 6., 5., 6.]])

In [13]:
array5=np.zeros((3,6))
array5[[0,1,2],[0,2,4]]=[1,3,5]
array5

x=np.zeros((3,6))
x[[0],[0,2,4]]=1
x[[0],[1,3,5]]=2
x[[1],[0,2,4]]=3
x[[1],[1,3,5]]=4
x[[2],[0,2,4]]=5
x[[2],[1,3,5]]=6
x

array([[1., 2., 1., 2., 1., 2.],
       [3., 4., 3., 4., 3., 4.],
       [5., 6., 5., 6., 5., 6.]])

In [16]:
a=np.zeros((3,6))
a[:,[0,2,4]]=[1,3,5]
a


array([[1., 0., 3., 0., 5., 0.],
       [1., 0., 3., 0., 5., 0.],
       [1., 0., 3., 0., 5., 0.]])

line space # seqence of equally spaced values between start and end
(start,stop,no of element)

In [9]:
a=np.linspace(1,10,15)
a

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])

ones

In [13]:
array6=np.ones(5)
array6

array([1., 1., 1., 1., 1.])

creating a range of array

In [4]:
array7=np.arange(1,10)
array7
array7=np.arange(1,10,2)
array7
array7=np.arange(10,1,-2)
array7

array([10,  8,  6,  4,  2])

In [6]:
a=np.full((3,3),'a')
a

array([['a', 'a', 'a'],
       ['a', 'a', 'a'],
       ['a', 'a', 'a']], dtype='<U1')

In [17]:
array8=np.array([[[1,2,3],
                [4,5,6]],

                [[1,2,3],
                [4,5,6]]])
array8

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
array9=np.array([1,2,3,4,5])
np.append(array9,6) # to add element in last



array([1, 2, 3, 4, 5, 6])

In [ ]:
array9=np.array([1,2,3,4,5])
np.insert(array9,2,7)      # insert multiple elements

array9=np.array([1,2,3,4,5])
np.insert(array9,2,[7,8])  # insert multiple elements



array([1, 2, 7, 8, 3, 4, 5])

#  insertion

In [ ]:
array10=np.array([[1,2],[3,4]])   #insert multiple element in row wise insertion
array11=np.insert(array10,1,[5,6],axis=0)
array11

array10=np.array([[1,2],[3,4]])   #insert multiple element in colomn wise insertion
array11=np.insert(array10,1,[5,6],axis=1)
array11

array([[1, 5, 2],
       [3, 6, 4]])

In [ ]:
# copy

array12=np.array([1,2,3,4,5])  # to copy from one to another
abc=np.copy(array12)
abc

array([1, 2, 3, 4, 5])

In [22]:
# sort 
array13=np.array([1,5,9,7,10])  # to sort
abcd=np.sort(array13)
abcd

array([ 1,  5,  7,  9, 10])

In [36]:
array13=np.array([1,5,9,7,10]) 
ab=np.delete(array13,2)
ab

array([ 1,  5,  7, 10])

In [46]:
array14=np.random.randint(1,10,(3,4))
array14

a=np.delete(array14,2,axis=1)
a

a=np.delete(array14,2,axis=0)
a

a=np.delete(array14,(2,3),axis=1)
a

array([[3, 6],
       [7, 8],
       [2, 7]], dtype=int32)

concatination

In [23]:
array14=np.array([1,2,3,4,5])
array15=np.array([6,7,8,9,10])  
np.vstack([array14,array15])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [24]:
array14=np.array([1,2,3,4,5])
array15=np.array([6,7,8,9,10])  
np.hstack([array14,array15])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a=np.random.randint(1,10,(3,3)) 
ab=np.random.randint(1,10,(3,3))     # V STACK
np.concatenate([a,ab],axis=0)

array([[7, 4, 1],
       [5, 4, 9],
       [5, 4, 5],
       [8, 5, 2],
       [6, 7, 9],
       [4, 2, 3]], dtype=int32)

In [53]:
a=np.random.randint(1,10,(3,3)) 
ab=np.random.randint(1,10,(3,3))     # H STACK
np.concatenate([a,ab],axis=1)

array([[2, 3, 3, 5, 2, 9],
       [2, 5, 7, 9, 4, 1],
       [1, 8, 8, 5, 9, 2]], dtype=int32)

# ravel (Covert 2d,3Dto 1d ARRAY)

In [ ]:
array16=np.array([[1,2,3,4,5],[6,7,8,9,10]])   # coverting 2D array to 1D array
np.ravel(array16)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Random Function

In [ ]:
array17=np.random.random(5)
array17


array17.itemsize
array17.size

8

In [26]:
array17=np.random.randint(2,10,5)
array17

array17.itemsize
array17.size

5

In [24]:
a=np.random.randint(1,10,(3,3))
a

a.size
a.itemsize

4

In [33]:
b=np.random.randint(1,10,5)
b
b=b.astype("float")
b
b.dtype

dtype('float64')

In [ ]:
array18=np.array([1,2,3,4,5]) #addition
array19=np.array([6,7,8,9,10])
sum=array18+array19
sum

array([ 7,  9, 11, 13, 15])

In [76]:
array3=np.array([[1,2,3,4,5],[6,7,8,9,10]])
array4=np.array([[1,2,3,4,5],[6,7,8,9,10]])
ab=array3*array4
ab

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100]])

In [87]:
array3=np.array([[1,2],[8,9]])
array4=np.array([[1,2],[6,7]])

arr=np.matmul(array3, array4)
arr

array([[13, 16],
       [62, 79]])

In [ ]:
array18=np.array([1,2,3,4,5]) #substraction
array19=np.array([6,7,8,9,10])
sum=array18-array19
sum

array([-5, -5, -5, -5, -5])

In [ ]:
array18=np.array([1,2,3,4,5]) #division
array19=np.array([6,7,8,9,10])
sum=array18/array19
sum

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [ ]:
array18=np.array([1,2,3,4,5]) #multiplication
array19=np.array([6,7,8,9,10])
sum=array18*array19
sum

array([ 6, 14, 24, 36, 50])

# slicing

#syntax
array[start:stop:step]
start-starting index(included)
stop-ending index(excluded)
step-interval between elements


In [25]:
array20=np.array([1,2,3,4,5,6,7,8,9,10])
array20[1:4]
array20[1:11]
array20[:8]
array20[2:]
array20[::2]

array([1, 3, 5, 7, 9])

In [4]:
a=np.random.randint(1,10,(3,3))
a


array3=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(array3)

array3[1,1]




[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


np.int64(7)

In [27]:
array3=np.array([[1,2,3,4,],[6,7,8,9,],[11,12,13,14],[16,17,18,19]])
array3
array3.diagonal()

array([ 1,  7, 13, 19])

In [ ]:
array3=np.array([[1,2,3,4,5],[6,7,8,9,10]])
array3

np.max(array3)
np.min(array3)
np.max(array3,axis=1)
np.min(array3,axis=1)
np.max(array3,axis=0)
np.min(array3,axis=0)

np.int64(1)

BOOLEAN  MASKING

In [29]:
array3=np.array([1,10,3,7,5,9,2])
mask=array3>5
print(mask)
print(array3[mask])

[False  True False  True False  True False]
[10  7  9]


In [30]:
a=np.random.randint(1,10,(3,6))
np.all(a>5,axis=1)  # 1 represent row

array([False, False, False])

In [31]:
array4=np.array([[1,2,3,4,5],
                [6,7,8,9,10],
                [1,2,3,4,5],
                [6,7,8,9,10]])
array4
np.any(array4>5,axis=1)    

array([False,  True, False,  True])

In [32]:
a=np.array([[1,2,3,4,5],
                [6,7,8,9,10],
                [1,2,3,4,5],
                [6,7,8,9,10]])
a
np.any(a>5,axis=0)     #represent 0 as coloum

array([ True,  True,  True,  True,  True])

In [33]:
a=np.array([[1,2,3,4,5],
                [6,7,3,9,10],
                [11,3,7,9,1],
                [3,4,9,5,1]])
np.all(a>5,axis=0)     #represent 0 as coloum

array([False, False, False, False, False])

#conditional selection 

new[new>5]

In [38]:
new=np.array([[1,2,3,4,5],
                [6,7,3,9,10],
                [11,3,7,9,1],
                [3,4,9,5,1]])

new[((new>5)&(new<8))]

array([6, 7, 7])

In [39]:
new=np.array([[1,2,3,4,5],
                [6,7,3,9,10],
                [11,3,7,9,1],
                [3,4,9,5,1]])

new[new%2==0]

array([ 2,  4,  6, 10,  4])

In [40]:
new=np.array([[1,2,3,4,5],
                [6,7,3,9,10],
                [11,3,7,9,1],
                [3,4,9,5,1]])
new[new%2!=0]

array([ 1,  3,  5,  7,  3,  9, 11,  3,  7,  9,  1,  3,  9,  5,  1])

UNION

In [47]:
A=np.array([1,2,2,3,4])
B=np.array([5,6,6,6,7])

union=np.union1d(A,B)
union

array([1, 2, 3, 4, 5, 6, 7])

array boardcasting

In [5]:
a=np.array([[1,2,2,3,4],[2,4,7,8,10],[11,22,33,44,55]])
b=np.array([5,6,6,6,7])
np.add(a,b)

array([[ 6,  8,  8,  9, 11],
       [ 7, 10, 13, 14, 17],
       [16, 28, 39, 50, 62]])

loading text file

In [7]:
import os
os.getcwd()

'c:\\Users\\adith\\python practice\\numpy'

In [14]:
data=np.genfromtxt("C:\\Users\\adith\\python practice\\numpy\\array1.txt",delimiter=',')
data

array([[ 1.,  2.,  2.,  3.,  4., nan],
       [ 2.,  4.,  7.,  8., 10., nan],
       [11., 22., 33., 44., 55., nan]])

QUESTIONS

In [43]:
# create a 3x3 matrix with value from 2 to 10

m=np.random.randint(2,10,(3,3))
m

array([[7, 6, 2],
       [3, 5, 8],
       [7, 9, 2]], dtype=int32)

In [ ]:
#write a numpy program to get unique elemrents
A=([1,2,4,4,5,5,7,8,8])
b=np.unique(a)
b

array([ 1,  2,  3,  4,  5,  6,  7,  9, 10, 11])

In [49]:
#write a numpy program to find the union of two arrays. union will return the unique,sorted array of values that are in either of the  two input array.

ar1=np.array([1,2,3,4,5])
ar2=np.array([4,5,6,7,8])

union=np.union1d(ar1,ar2)
union

array([1, 2, 3, 4, 5, 6, 7, 8])

In [56]:
#write a numpy program to create a 2D array of size 2X3 (composed of 4 byte integer elements),also print shape ,type and data type of the array

a=np.array([[1,2,3],[6,7,8]])
a

a.shape
a.dtype
type(a)

numpy.ndarray

In [ ]:
 #create a 2D array with diagonals  [4,5,6,8]
diag=np.diag([4,5,6,8])

diag

array([[4, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 8]])

In [ ]:
#write a numpy program to an array converted to a float type

b=np.random.randint(1,10,5)
b
b=b.astype("float")  #  converting to float using  astype()
b

b.dtype

dtype('float64')

In [5]:
#write a numpy program to create a 8x8 matrix and fill it with a checkboard pattern


m=np.zeros((8,8))
m[::2,1::2]=1
m[1::2,::2]=1
m

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [ ]:
#Write a NumPy program to convert the values of Centigrade degrees into Fahrenheit degrees.Centigrade values are stored into a NumPy array

In [6]:
#Write a NumPy program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements.

arr=np.array([10,20,30,40,50])

noelement= arr.size


elementsize= arr.itemsize
bytes=arr.nbytes

arr
noelement


elementsize
bytes

40

In [ ]:
#Write a NumPy program to test whether each element of a 1-D array is also present in a second array.

array1=np.array([1,2,3,4,5])
array2=np.array([2,4,6,8])


In [ ]:
#Write a NumPy program to find common values between two arrays

array1=np.array([1,2,3,4,5])
array2=np.array([3,4,5,6,7])
